version: '3.8'

include:
  - path: ./src/infra/docker-compose/docker-compose.elk.yml
    env_file:  ./src/infra/configs/elk.env
  - path: ./src/infra/docker-compose/docker-compose.kafka.yml
  - path: ./src/infra/docker-compose/docker-compose.mongo.yml
  - path: ./src/infra/docker-compose/docker-compose.postgresql.yml
  - path: ./src/infra/docker-compose/docker-compose.redis.yml
  - path: ./src/infra/docker-compose/docker-compose.nginx.yml
  - path: ./src/infra/docker-compose/docker-compose.variables.yml