version: '3.8'

services:
  nginx:
    build: ../nginx/
    image: seges/nginx-consul
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      #      templates
      - "../configs/nginx-setup/templates/template.ctmpl:/etc/consul-template/templates/template.ctmpl"
      #      config
      - "../configs/nginx-setup/conf:/etc/consul-template/conf"
    depends_on:
      - consul
  
  consul:
    image: consul:1.15.4
    command: consul agent -server -client=0.0.0.0 -bootstrap-expect=3 -data-dir=/tmp/consul -ui
    hostname: consul
    ports:
      - "8301:8300"
      - "8401:8400"
      - "8501:8500"
      - "8601:8600"
      - "9001:9001"